
/* ================= 第三名守夜人：萤 · 灯匠学徒 =================
 * 定位：小型卡 + 【机】，靠数量与充能打节奏。晨钟城老钟表匠的学徒，
 * 师父出城前把怀表的齿轮分给了城墙（见“发条”的传闻），她留下来守着全城的灯。
 */
Object.assign(ITEMS,{
  firefly:{n:'萤灯',size:1,tag:'机',t:0,up:'cd',cd:1.3,dmg:3,fx:'firefly',hero:'ying',d:'放出3只萤火，分别飞向最前方的3个敌人。',f:'一盏灯能照亮一段墙。三只萤火能照亮三个坏消息。'},
  musicbox:{n:'八音盒',size:2,tag:'机',t:1,up:'cd',cd:2.6,dmg:0,fx:'none',chargeSmall:.2,hero:'ying',d:'触发时，为棋盘上所有其他小型卡充能20%，品质越高充得越多。',f:'只会放一首曲子。师父说，一首就够了。'},
  pendulum:{n:'大钟摆',size:3,tag:'机',t:2,up:'mix',cd:3.4,dmg:26,fx:'sweep',hero:'ying',d:'钟摆横扫：伤害与目标同一水平线上的所有敌人。',f:'钟楼停摆的那天，她把钟摆拆了下来。'},
  oilspill:{n:'泼灯油',size:1,tag:'火',t:0,up:'dmg',cd:1.2,dmg:2,fx:'spark',burn:2,hero:'ying',d:'泼出一勺灯油，点燃目标，每秒灼烧，持续3秒。',f:'灯油是用来点灯的。偶尔，也用来点别的。'},
  fuse:{n:'引信',size:1,tag:'火',t:1,up:'cd',cd:2.8,dmg:0,fx:'none',fuse:{tag:'火',amt:.15},hero:'ying',d:'触发时，为所有【火】卡充能15%，品质越高充得越多。',f:'一根线，点着一整片火。'},
  dragonlantern:{n:'火龙灯',size:3,tag:'火',t:2,up:'mix',cd:4.0,dmg:30,fx:'meteor',aoe:36,burn:8,hero:'ying',d:'放飞火龙灯，陨火天降，大范围伤害并留下烈焰。',f:'师父说，灯飞得越高，火就落得越远。'},
  paperlamp:{n:'纸灯',size:1,tag:'火',t:0,up:'dmg',cd:1.4,dmg:3,fx:'spark',burn:2,hero:'ying',d:'放飞一盏小纸灯，点燃目标。',f:'有愿望找灯，没愿望也找灯。'},
  gear:{n:'飞齿轮',size:1,tag:'机',t:0,up:'cd',cd:1.2,dmg:4,fx:'knife',hero:'ying',d:'掷出锋利的齿轮，命中前方敌人。',f:'师父的钟表里多余的零件。'},
  windup:{n:'上弦钥匙',size:1,tag:'机',t:0,up:'cd',cd:2.6,dmg:0,fx:'none',charge:.12,hero:'ying',d:'触发时为左右相邻的卡充能12%，品质越高充得越多。',f:'咔哒咔哒，转起来。'},
  firecracker:{n:'爆竹',size:1,tag:'火',t:0,up:'dmg',cd:1.8,dmg:5,fx:'shell',aoe:12,hero:'ying',d:'噼里啪啦的小爆炸。',f:'过年剩的。威力可没剩。'},
  paperkite:{n:'纸鸢',size:2,tag:'机',t:1,up:'cd',cd:2.4,dmg:7,fx:'firefly',hero:'ying',d:'纸鸢带着火星，飞向最前方的3个敌人。',f:'线在她手里，火在天上。'},
  lamplight:{n:'灯阵',size:2,tag:'火',t:1,up:'dmg',cd:2.8,dmg:10,fx:'flame',aoe:20,burn:3,hero:'ying',d:'一排灯同时点亮，火光横扫一片敌人。',f:'整条街的灯，一起亮。'},
  clockwork:{n:'发条兵',size:2,tag:'机',t:1,up:'dmg',cd:2.2,dmg:13,fx:'arrow',pierce:1,hero:'ying',d:'发条小兵射出弩箭，穿透目标身后1个敌人。',f:'上满弦，它比谁都勇敢。'},
  beacon:{n:'灯塔',size:3,tag:'机',t:2,up:'cd',cd:5.2,dmg:14,fx:'bell',chargeAll:.2,hero:'ying',d:'灯塔之光扫过射程内所有敌人，并为其他所有卡充能20%。',f:'光到之处，皆是城墙。'},
  oilpot:{n:'添油',size:1,tag:'火',t:1,up:'cd',cd:2.6,dmg:0,fx:'none',charge:.2,hero:'ying',d:'为灯添油：为左右相邻的卡充能20%，品质越高充得越多。',f:'油满了，灯就亮了，仗就打赢了。'},
  moth:{n:'飞蛾',size:2,tag:'火',t:1,up:'dmg',cd:2.6,dmg:14,fx:'fslash',burn:3,hero:'ying',d:'扑火的飞蛾带着火焰斩向目标，并波及身旁的敌人。',f:'它知道会烧起来。它还是去了。'},
  mainspring:{n:'主发条',size:3,tag:'机',t:2,up:'mix',cd:3.8,dmg:30,fx:'sweep',hero:'ying',d:'巨大的发条横扫，与目标同一水平线上的敌人全都遭殃。',f:'这是师父的怀表里最粗的那根。'},
  skylantern:{n:'孔明灯',size:2,tag:'火',t:1,up:'mix',cd:3.2,dmg:8,fx:'meteor',aoe:24,burn:4,hero:'ying',d:'孔明灯升空引下天火，大范围伤害并点燃敌人。',f:'写满愿望的灯，掉下来的时候最亮。'},
  toolbox:{n:'工具箱',size:1,tag:'机',t:1,up:'cd',cd:3.4,dmg:0,fx:'none',buff:.35,hero:'ying',d:'触发时，左右相邻卡的下一次攻击伤害 +35%。',f:'锤子，扳手，胜利。'}
});
addSprites({
paperlamp:[
"...kkkkk....",
"..kooooook..",
".kooYYYYook.",
".koYYyyYYok.",
".koYYyyYYok.",
".kooYYYYook.",
"..kooooook..",
"...kkkkk....",
".....kk.....",
"............",
"............",
"............"],
gear:[
"...kk.kk....",
"....kkk.....",
"..kkgggkk...",
"..kgggggk...",
".kgggkgggk..",
".kggkkkggk..",
".kggkkkggk..",
".kgggkgggk..",
"..kgggggk...",
"..kkgggkk...",
"....kkk.....",
"...kk.kk...."],
windup:[
"..kkk.......",
".kNNk.......",
".kNNk.......",
".kNNkkkkk...",
".kNNNNNNNk..",
"..kNNNNNNk..",
"...kNNNk....",
"....knk.....",
"....knk.....",
"....knk.....",
"...knnk.....",
"...kk......."],
firecracker:[
".....k......",
"....kYk.....",
"...kRRRk....",
"...kRrRk....",
"...kRRRk....",
"...kRrRk....",
"...kRRRk....",
"...kRrRk....",
"...kRRRk....",
"....kkk.....",
"............",
"............"],
paperkite:[
".....k......",
"....kYk.....",
"...kYYYk....",
"..kYYyYYk...",
".kYYyyyYYk..",
"..kYYyYYk...",
"...kYYYk....",
"....kYk.....",
".....k......",
"....kYk.....",
"...kYk......",
"..kYk......."],
lamplight:[
"..k..k..k...",
".koo.koo.koo",
".koY.koY.koY",
".koo.koo.koo",
"..k..k..k...",
"..k..k..k...",
"..k..k..k...",
"..k..k..k...",
".kkk.kkk.kkk",
"............",
"............",
"............"],
clockwork:[
"....kkkk....",
"...knnnnk...",
"...knwwnk...",
"...knwwnk...",
"...knnnnk...",
"....knnk....",
"..kknnnnkk..",
"..knknnknk..",
"....knnk....",
"...knnnnk...",
"...kn..nk...",
"...kk..kk..."],
beacon:[
"....kYYk....",
"...kYYYYk...",
"...kYYYYk...",
"....kYYk....",
"...kNNNNk...",
"...kNnnNk...",
"..kNNNNNNk..",
"..kNnnnnNk..",
"..kNNNNNNk..",
".kNNNNNNNNk.",
".kkkkkkkkkk.",
"............"],
oilpot:[
"............",
"..kk........",
".kNNk.......",
".kNNk.......",
"kNNNNNNk....",
"kNnnnnnNNk..",
"kNnYYnnnNk..",
"kNnnnnnNNk..",
".kNNNNNNk...",
"..kkkkkk....",
"............",
"............"],
moth:[
".kk......kk.",
"kYYk....kYYk",
"kYyYk..kYyYk",
".kYyYkkYyYk.",
"..kYyYYyYk..",
"...kYYYYk...",
"....kYYk....",
"....knnk....",
".....kk.....",
"............",
"............",
"............"],
mainspring:[
"............",
"..kkkkkkkk..",
".kNNNNNNNNk.",
".kNnNNNNnNk.",
".kNNNNNNNNk.",
"..kNNNNNNk..",
"...kkkkkk...",
"............",
"............",
"............",
"............",
"............"],
skylantern:[
"...kkkkk....",
"..kooooook..",
".kooYYYYook.",
".koYYyyYYok.",
".koYYyyYYok.",
".kooYYYYook.",
"..kooooook..",
"...kooook...",
"....kook....",
".....k......",
"............",
"............"],
toolbox:[
"............",
"...kkkkk....",
"..kNNk......",
"..kNNk......",
".kNNNNNNNk..",
".kNwNNgNNk..",
".kNNNNNNNk..",
".kNNNNNNNk..",
".kNNNNNNNk..",
"..kkkkkkk...",
"............",
"............"]});
addSprites({
oilspill:[
"....kk......",
"...kNNk.....",
"..kNnnNk....",
"..kNnYNk....",
".kNNnnnNNk..",
"kNoooooooNk.",
"kNooYYooNk.",
".kooooooook.",
"..kkkkkkk...",
"............",
"............",
"............"],
fuse:[
".....kYk....",
"....kYoYk...",
"...kYoYk....",
"..kYoYk.....",
".kYoYk......",
"kYoYk.......",
"kYk.........",
"kk..........",
"............",
"............",
"............",
"............"],
dragonlantern:[
"...kkkkkk...",
"..kRRRRRRk..",
".kRrrrrrrRk.",
".kRrkookrRk.",
".kRrkookrRk.",
".kRrrrrrrRk.",
"..kRRRRRRk..",
"....kRRk....",
"....kRk.....",
"...kRk......",
"...kk.......",
"............"]});
Object.assign(RELICS,{
  pocketwatch:{n:'师父的怀表',t:1,ico:'orb:y',hero:'ying',m:{spd:.08,startCharge:.1},f:'表盖内侧刻着：别等天亮，去点灯。'},
  jarflies:{n:'萤火虫罐',t:0,ico:'potion:l',hero:'ying',m:{s1:.15},f:'一罐子光，够照亮一段城墙。'},
  earring:{n:'齿轮耳坠',t:0,ico:'ring:y',hero:'ying',m:{'tag_机':.1,crit:.02},f:'左耳一个，右耳一个，走路会响。'},
  oilcan:{n:'灯油壶',t:2,ico:'potion:N',hero:'ying',m:{s1:.2,spd:.06},f:'每盏灯每晚一勺。七百年，一天没落下。'},
  lampbook:{n:'全城的灯谱',t:3,ico:'book:y',u:1,hero:'ying',m:{dmg:.2,s1:.3},f:'记着晨钟城每一盏灯的位置。七百年来，只熄过一盏。'}
});
HEROES.ying={n:'萤',title:'灯匠学徒',col:'#ffd166',portrait:'p_ying',wall:26,gold:10,start:[['firefly',0,3],['clock',1,4]],
  tag:'擅长小型卡与【机】',desc:'老钟表匠的学徒，守着全城的灯。小卡越多越强，擅长充能与节奏。专属：八音盒、大钟摆。',
  intro:'师父说，只要还有一盏灯亮着，这座城就还没输。我负责让它们一直亮着。'};
TREES.ying=[
  {n:'灯',c:'#ffd166',nodes:[{n:'小灯',m:{s1:.15}},{n:'灯串',m:{left:.2,right:.2}},{n:'万家灯火',m:{s1:.3,full:.2}}]},
  {n:'钟',c:'#c99a6b',nodes:[{n:'上弦',m:{startCharge:.2}},{n:'校准',m:{spd:.1}},{n:'报时',m:{'tag_机':.25,spd:.05}}]},
  {n:'光',c:'#fff4cf',nodes:[{n:'反光',m:{crit:.06}},{n:'聚光',m:{critDmg:.6}},{n:'黎明之前',m:{dmg:.15,crit:.06}}]}
];
TREE_SAY.ying=[
  ['一盏小灯，也能让人看清脚下。','把灯连起来，墙就不会有暗处。','你看——整座城都亮了。'],
  ['先上弦，再开工。师父的规矩。','差一秒都不行。齿轮会记仇的。','当——当——当。现在是守夜时间。'],
  ['光打在盔甲上，会告诉你哪里有缝。','把所有的光，收在一个点上。','天亮之前，是最亮的时候。我一直这么相信。']
];
/* 台词：给现有的按人物区分的文本补上萤 */
const _Y={
  chain:['叮叮当当——全都转起来了！','就像师父的钟，一个带动一个！'],crit:['正中！','这一下，比钟声还响。'],
  hurt:['墙上的灯灭了一盏！','别碰我的灯！'],low:['灯……还剩几盏？不，别数了！','只要还有一盏亮着！'],
  freeze:['齿轮卡住了！'],surge:['好多火把……比城里的灯还多。','所有的灯，全都点起来！']
};
for(const k in _Y)if(BARKS[k])BARKS[k].ying=_Y[k];
FOEB.knight.low.ying='小姑娘……你的灯……让我想起……';
FOEB.knight.heroLow.ying='卡尔大叔？你以前每天晚上都来钟楼跟师父下棋的！';
FOEB.eye.low.ying='灯匠的学徒。你的师父出城时，是我收下了他。';
FOEB.eye.heroLow.ying='师父……？那我就把光送进去，把他找回来！';
const _YN=['第一晚？别怕，我把灯都点亮了。','地底下有声音……像生锈的齿轮。','汉斯爷爷……他以前每天帮我扛梯子。','那面盾……卡尔大叔以前总把它擦得锃亮。',
  '灰袍？师父出城那天，就是去学院找他。','它们的投石车……是照着我们的图纸做的！','孩子们在搬砖，我去给每段墙都点上灯。','你吞掉了太阳。那我就从这里，一盏一盏把光点回去。'];
NIGHTS.forEach((N,i)=>{for(const b of N.beats)if(b[1]==='hero'&&typeof b[2]==='object')b[2].ying=_YN[i];});
if(STORY.win)for(const p of STORY.win)if(p.who==='hero'&&typeof p.t==='object')p.t.ying='全城的灯都还亮着。师父，你看得见吗？天亮了。';
if(STORY.lose)for(const p of STORY.lose)if(p.who==='hero'&&typeof p.t==='object')p.t.ying='灯……灭了。可是灯芯还在，下次还能点。';
Object.assign(LORE,{
  firefly:['萤小时候怕黑，师父给她做了一盏会自己飞的灯。后来她把这手艺教给了全城的孩子。','第一盏灯','那盏灯至今挂在钟楼顶上。它是整座城最后熄灭的东西——如果真有那一天的话。'],
  musicbox:['老钟表匠只会做一首曲子。他说曲子不在多，在于每个齿轮都知道自己什么时候该转。','师父的曲子','萤从没听完过这首曲子。最后一小节，要等师父回来才上弦。'],
  pendulum:['钟楼的大钟摆了七百年。钟停的那一夜，萤爬上去把钟摆拆了下来，扛上了城墙。','停摆的那一夜','它每摆一下，城里的钟就好像又走了一秒。']
});
for(const k of['firefly','musicbox','pendulum']){const[l,dn,dl]=LORE[k];Object.assign(ITEMS[k],{lore:l,dn,dl});}
